#!/bin/bash
source "$( dirname "$(readlink -f "$0")" )/_variables"

# backup
#
# This file is run on the host, and backs up any configuration
# or data stored outside /config.
#
# Examples are database backups etc (which we might want to
# stop any running services to do).
#
# Backups need to be stored in BACKUPPATH or into a path specified
# in volumes.  We can use whatever format we want for the files, 
# we restore them in the restore script.
#

BACKUPPATH="$1"


