#!/bin/bash
source "$( dirname "$(readlink -f "$0")" )/_variables"

# SERVICENAME and IMAGENAME are provided by _variables.
cat <<EOF >&2
   
NAME
   ${SERVICENAME} - Runs minecraft
       
SYNOPSIS
   ${SERVICENAME} help            - This help
   ${SERVICENAME} configure PORT  - Configure for port PORT
   ${SERVICENAME} run             - Make it go!
   
DESCRIPTION
   Built from ${IMAGENAME}.
EOF