#!/bin/bash
source "$( dirname "$(readlink -f "$0")" )/_variables"

# install
#
# This file is run on the host, and can be used to do things like
# set up docker volumes (e.g. docker volume create dr-helloworld-datavol )
#
#

