#!/bin/bash
source "$( dirname "$(readlink -f "$0")" )/_variables"

# restore
#
# This file is run on the host, and restores any configuration or data
# that is outside /config from the backup in RESTOREPATH.
#

RESTOREPATH="$1"

