language: cpp
sudo: required
dist: trusty
before_install:
   - wget -nv https://drunner.s3.amazonaws.com/lin/install_drunner_travis.sh
   - /bin/bash install_drunner_travis.sh
   - export PATH=$PATH:$HOME/.drunner/bin/

script:
   - ddev build
   - ddev test
   - minecraft configure PORT=55555
   - minecraft start
   - minecraft info
   - minecraft stop
