#!/bin/bash
                                                                                                                                                          
#  ad88888ba                                        88                          88888888ba                                                                  
# d8"     "8b                                       ""                          88      "8b                                                                 
# Y8,                                                                           88      ,8P                                                                 
# `Y8aaaaa,     ,adPPYba,  8b,dPPYba,  8b       d8  88   ,adPPYba,   ,adPPYba,  88aaaaaa8P'  88       88  8b,dPPYba,   8b,dPPYba,    ,adPPYba,  8b,dPPYba,  
#   `"""""8b,  a8P_____88  88P'   "Y8  `8b     d8'  88  a8"     ""  a8P_____88  88""""88'    88       88  88P'   `"8a  88P'   `"8a  a8P_____88  88P'   "Y8  
#         `8b  8PP"""""""  88           `8b   d8'   88  8b          8PP"""""""  88    `8b    88       88  88       88  88       88  8PP"""""""  88          
# Y8a     a8P  "8b,   ,aa  88            `8b,d8'    88  "8a,   ,aa  "8b,   ,aa  88     `8b   "8a,   ,a88  88       88  88       88  "8b,   ,aa  88          
#  "Y88888P"    `"Ybbd8"'  88              "8"      88   `"Ybbd8"'   `"Ybbd8"'  88      `8b   `"YbbdP'Y8  88       88  88       88   `"Ybbd8"'  88          



#------------------------------------------------------------------------------------
# Initialisation of globals.

set -o nounset
MYDIR=$( dirname "$(readlink -f "$0")" )
source "$MYDIR/_variables"
e=$(printf "\e") 
readonly CODE_S="$e[32m"
readonly CODE_E="$e[0m"

#------------------------------------------------------------------------------------
# die MSG [EXITCODE] - show the message (red) and exit exitcode.

function die { 
   echo " ">&2 ; echo -e "\e[31m\e[1m${1}\e[0m">&2  ; echo " ">&2
   EXITCODE=${2:-1}
   exit "$EXITCODE"
}

#------------------------------------------------------------------------------------
# showhelp - give some info about the service. SERVICENAME and IMAGENAME are provided by _variables.

function showhelp {
cat <<EOF >&2

NAME
   ${SERVICENAME} - Runs minecraft
       
SYNOPSIS
   ${SERVICENAME} help            - This help
   ${SERVICENAME} configure PORT  - Configure for port PORT
   ${SERVICENAME} start           - Make it go!
   ${SERVICENAME} stop            - Stop it
   ${SERVICENAME} status          - Is it running?
   
   ${SERVICENAME} export PATH     - export world and config to PATH
   ${SERVICENAME} import PATH     - import world and config from PATH
   
DESCRIPTION
   Built from ${IMAGENAME}.
   
EOF
}

#------------------------------------------------------------------------------------
# Run a command in the container. 

function dockerrun {
   local RVAL=0
   docker run "${COMMANDOPTS[@]}" --name="${SERVICENAME}-${COMMAND}" -h "${HOSTNAME}" "${DOCKEROPTS[@]}" "${IMAGENAME}" "$@"
   RVAL=$?
   docker rm "${SERVICENAME}-${COMMAND}" >/dev/null
   [ $RVAL -eq 0 ] || die "${SERVICENAME} ${COMMAND} failed."
}

# detached, can't remove.
function dockerrund {
   docker run -d "${COMMANDOPTS[@]}" --name="${SERVICENAME}-${COMMAND}" -h "${HOSTNAME}" "${DOCKEROPTS[@]}" "${IMAGENAME}" "$@"
   [ $? -eq 0 ] || die "${SERVICENAME} ${COMMAND} failed."
}

#------------------------------------------------------------------------------------
# See if a container is exists. Return value of docker inspect is correct (0 if running)
# https://gist.github.com/ekristen/11254304

function container_exists {
   # exit code of docker inspect says if it's running.
   docker inspect --format="{{ .State.Running }}" "$1" >/dev/null 2>&1
}

#------------------------------------------------------------------------------------
# See if a container is running

function container_running {
   container_exists "$1" || return 1
   local RUNNING=$(docker inspect --format="{{ .State.Running }}" "$1" 2>/dev/null)
   [ "${RUNNING}" = "true" ]
}

#------------------------------------------------------------------------------------
# See if a container is paused

function container_paused {
   container_exists "$1" || return 1
   local PAUSED=$(docker inspect --format="{{ .State.Paused }}" "$1" 2>/dev/null)
   [ "${PAUSED}" = "true" ]
}

#------------------------------------------------------------------------------------
# Get the port from the configuration file.

function getPort {
   PORT=$(docker run -i --name="${SERVICENAME}-getport" "${DOCKEROPTS[@]}" "${IMAGENAME}" bash -c "cat /config/port")
   RVAL=$?
   docker rm "${SERVICENAME}-getport" >/dev/null 2>&1
   [ "$RVAL" -eq 0 ] || die "Failed to get port. Please run configure first."
   [ -n "$PORT" ] || die "Run configure first!"
}

#------------------------------------------------------------------------------------
# Determine the host ip. See http://stackoverflow.com/a/25851186

function getHostIP {
   HOSTIP=$(ip route get 1 | awk '{print $NF;exit}')
}

#------------------------------------------------------------------------------------
# Display the status of hte service.

function showStatus {
   container_exists "${SERVICENAME}-start"  || { echo "${SERVICENAME}'s container is stopped and removed." ; exit 0 ; }
   container_running "${SERVICENAME}-start" || { echo "${SERVICENAME}'s container is stopped but not removed." ; exit 0 ; }
   getPort
   getHostIP
   echo "Minecraft is running on ${HOSTIP}:${PORT}"   
}

#------------------------------------------------------------------------------------
# The main function. We can add any commands we'd like here!

function main {
   [ "$#" -gt 0 ] || die "servicerunner must have the install argument."

   COMMAND="${1}" ; shift
   COMMANDOPTS=("-i")
   
   case "$COMMAND" in 
         install)
            ;;
            
         destroy)
            ;;
                     
         backupstart)
            # data volume is automatically backed up, we just need to pause the service so it's
            # warm not hot!
            #BACKUPPATH="$1"
            ! container_running "${SERVICENAME}-start" || docker pause "${SERVICENAME}-start"
            ;;

         backupend)
            # resume if paused.
            #BACKUPPATH="$1"
            ! container_paused "${SERVICENAME}-start" || docker unpause "${SERVICENAME}-start" 
            ;;
         
         restore)
            #RESTOREPATH="$1"
            ;;
         
         help)
            showhelp
            ;;
         
         enter)
            COMMANDOPTS=("-it")
            dockerrun /bin/bash "$@"
            ;;
         
         update)
            ;;

         start)
            ! container_running "${SERVICENAME}-start" || die "Already running" 3 
            ! container_exists "${SERVICENAME}-start"  || docker rm "${SERVICENAME}-start" >/dev/null 2>&1

            getPort
            COMMANDOPTS=("-p=${PORT}:25565" "-p=${PORT}:25565/udp" "--restart=always")
            dockerrund java -jar /minecraft_server.1.8.7.jar                          
            [ $? -eq 0 ] || die "Failed to launch minecraft on port $PORT :("
            showStatus
            ;;
         
         configure)
            ! container_running "${SERVICENAME}-start" || die "Can't configure while ${SERVICENAME} is started. Stop it first."
            [ "$#" -eq 1 ] || { showhelp ; die "You need to specify the PORT."; }
            PORT="$1"
            
            dockerrun bash -c "echo -n $PORT > /config/port && echo eula=true > /data/eula.txt"
            ;;

         stop)
            # check if running, if so stop it.
            ! container_running "${SERVICENAME}-start" || docker stop --time=30 "${SERVICENAME}-start" >/dev/null 2>&1
            ! container_exists "${SERVICENAME}-start"  || docker rm "${SERVICENAME}-start" >/dev/null 2>&1
            echo "New Status:"
            showStatus   
            ;;
         
         status)
            showStatus
            ;;
            
         import)
            [ "$#" -eq 1 ] || die "Import requires one argument (the path to of the world to be imported)."
            [ -d "$1" ] || die "Path does not exist: $1"
            ! container_running "${SERVICENAME}-start" || die "Can't import while ${SERVICENAME} is started. Stop it first."
            
            dockerrun bash -c "rm -r /data/*"
            tar cf - -C "$1" . | docker run -i --name="${SERVICENAME}-${COMMAND}" "${DOCKEROPTS[@]}" "${IMAGENAME}" tar -xv -C /data
            RVAL=$?
            docker rm "${SERVICENAME}-${COMMAND}" >/dev/null
            [ $RVAL -eq 0 ] || die "${SERVICENAME} ${COMMAND} failed to transfer the files."
            ;;
            
         export)
            [ "$#" -eq 1 ] || die "Export requires one argument (the path to export the world to)."
            [ -d "$1" ] || die "Please create the path first, e.g. ${CODE_S}mkdir -p ${1}${CODE_E}"
            ! container_running "${SERVICENAME}-start" || die "Can't export while ${SERVICENAME} is started. Stop it first with ${CODE_S}${SERVICENAME} stop${CODE_E}"
            
            docker run -i --name="${SERVICENAME}-${COMMAND}" "${DOCKEROPTS[@]}" "${IMAGENAME}" tar cf - -C "/data" . | tar -xv -C "$1" 
            RVAL=$?
            docker rm "${SERVICENAME}-${COMMAND}" >/dev/null
            [ $RVAL -eq 0 ] || die "${SERVICENAME} ${COMMAND} failed to transfer the files."
            ;;            
            
         *)
            showhelp
            die "Unrecognised command ${CODE_S}${COMMAND}${CODE_E}"            
            ;;
   esac
}

#------------------------------------------------------------------------------------

main "$@"
